#!/bin/sh
mkdir --parents "/var/log/Let's Encrypt"
 
"/opt/Let's Encrypt/letsencrypt-auto" renew 2>&1 >> "/var/log/Let's Encrypt/renew.log"
if [ $? -ne 0 ]; then
    echo Automated renewal failed, see "/var/log/Let's Encrypt/renew.log" for details
    exit 1
fi
exit 0

